name: Build and deploy

on:
  push:
    branches:
      - master
        
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build Docker image to run tests and deploy to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker build --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} -t ${{github.repository}}:${{github.sha}} .